server:
  port: 8882  #启动端口

# 以下是bootstrap.yaml拉取nacos配置中心文件内容后，需要填入的值
db:
  host: 120.26.0.232:3306
  name: diary_writing
  user: diary_writing
  password: microArch2023

maven-name: diaryWriting

spring:
#  rabbitmq:
#    host: 120.26.0.232
#    port: 5672
#    username: "music"
#    password: "musicListen"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.0.232:3306/diary_writing?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: diary_writing
    password: microArch2023
    initialSize: 20
    minIdle: 50
    maxActive: 500
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true  # 日志中显示 sql 语句
    hibernate:
      ddl-auto: update  # 自动更新
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL8Dialect