<template>
    <v-card
      class="mx-auto"
      max-width="344"
      min-width="80%"
      hover
    >
      <v-card-item>
        <v-card-title>
          推荐音乐室卡
        </v-card-title>
        <v-card-subtitle>
          推荐音乐室卡
        </v-card-subtitle>
      </v-card-item>
  
      <v-card-text>
        一些信息
      </v-card-text>
    </v-card>
  </template>