server:
  port: 8886  #启动端口
spring:
  cloud:
    gateway:
      locator:
        enabled: true
        lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins:
              - "http://localhost:8082"
              - "http://localhost:8881"
              - "http://localhost:8111"
              - "http://localhost:8887"
              - "http://localhost:8888"
              - "http://localhost:8889"
              - "http://localhost:*"
              - "http://120.26.0.232"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTIONS
      routes:
        - id: music-room-service
          uri: lb://music-room-service      # 按照注册在 nacos 上的服务名获取实例
          predicates:
            - Path=/music_room/**           # 匹配所有以 music_room 开头的路由
          filters:
            - StripPrefix=1                 # 转发的时候去掉 第一个 这里即 music_room

        - id: diary-writing-service
          uri: lb://diary-writing-service
          predicates:
            - Path=/diary/**
          filters:
            - StripPrefix=1

        - id: music-listen-service
          uri: lb://music-listen-service
          predicates:
            - Path=/music_listen/**
          filters:
            - StripPrefix=1

        - id: emotion-service
          uri: lb://emotion-service
          predicates:
            - Path=/emotion/**
          filters:
            - StripPrefix=1
  application:
    name: gateway
