server:
  port: 8886  #启动端口
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins:
              - "localhost://*"
              - "http://localhost:8082"
              - "http://localhost:*"
              - "http://120.26.0.232"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      routes:

    application:
      name: gateway
