server:
  port: 8887  #启动端口
spring:
  application:
    name: login-service   #服务名
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 120.26.0.232:8848   #nacos注册中心地址
  datasource:
    url: jdbc:mysql://120.26.0.232:3306/social
    username: social
    password: microArch2023
    hikari:
      max-lifetime: 60000 # 一分钟
mybatis:
  configuration:
    map-underscore-to-camel-case: true
