server:
  port: 8887  #启动端口
spring:
  application:
    name: login-service   #服务名
  cloud:
    nacos:
      # 服务注册与发现
      discovery:
        server-addr: 120.26.0.232:8848  # nacos地址
        namespace: 2023                 # 命名空间ID
        group: dev                      # 群组名称（自己设定，将服务进行逻辑分组）
        username: nacos                 # 用户名
        password: microArch2023         # 密码
      # 拉取nacos配置中心文件
      # 若不确定要不要拉取，可以先注释掉下面到datasource前两个config下的内容
      # 注释了之后一定要把pom.xml里的spring-cloud-starter-alibaba-nacos-config依赖移除，否则会报错
      config:
        server-addr: 120.26.0.232:8848  # nacos地址
        namespace: 2023                 # 命名空间ID
        group: DEFAULT_GROUP            # 群组名称（自己设定，将服务进行逻辑分组）
        username: nacos                 # 用户名
        password: microArch2023         # 密码
        name: login-service             # 文件名（缺省则是微服务的名字）
        file-extension: yaml            # 文件后缀
        context-path: /nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  datasource:
    url: jdbc:mysql://120.26.0.232:3306/social
    username: social
    password: microArch2023
    hikari:
      max-lifetime: 60000 # 一分钟

# 配置mybatis信息
mybatis:
  # mapper-locations: classpath:mapper/*Mapper.xml   # mapper映射文件路径
  # 包扫描路径，一般设置成model包的位置
  # 这样在mapper.xml里面写resultType和parameterType的时候只写model类名就行
  # 大小写均无要求，字母正确即可。比如说model类叫User，USER、uSEr都行
  type-aliases-package: cn.edu.tongji.login.model
  configuration:
    map-underscore-to-camel-case: true  # 将下划线字段名转换为驼峰命名
