server:
  port: 8889  #启动端口

# 以下是bootstrap.yaml拉取nacos配置中心文件内容后，需要填入的值
db:
  host: 120.26.0.232:3306
  name: music_room
  user: music_room
  password: microArch2023

maven-name: musicRoom

spring:
  cloud:
    sentinel:
      transport:
        port: 8899 # 与sentinel-dashboard通信端口，如果被占用会自动向后扫描
        dashboard: 121.40.220.228:8858