server:
  port: 8888  #启动端口

# 以下是bootstrap.yaml拉取nacos配置中心文件内容后，需要填入的值
db:
  host: 120.26.0.232:3306
  name: music_listen
  user: music_listen
  password: microArch2023

maven-name: musicListen

spring:
  rabbitmq:
    host: 120.26.0.232
    port: 5672
    username: "music"
    password: "musicListen"